### ISSUE TITLE
DenseNet wanted

### ISSUE THREAD

**Issue by JiHanFly** [SnailTyan/deep-learning-papers-translation#1]
I read the list of the collected thesis ，ResNet can be found，but  the more adanced／efficient convolutional network arctive ——DenseNet can not be found， are you interested in translating it for us Chinese learner？

**Comment by SnailTyan** [comment]
I have read DenseNet paper and tested DenseNet by Caffe. I think that DenseNet is not suitable to use in projects. So I didn't translate it. I'll think about your requirement.
