### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jovahe** [SnailTyan/deep-learning-papers-translation#10]
In the paper "Feature Pyramid Networks for Object Detection", some sentences do not translate correctly, such as:
"we rely on an architecture that combines low-resolution, semantically strong features with high-resolution, semantically weak features  via a top-down pathway and lateral connections "
Translation is : "我们依赖于一种结构，它将低分辨率，具有高分辨率的强大语义特征，语义上的弱特征通过自顶向下的路径和横向连接相结合。"
Correct translation may be: "我们所依赖的架构将低分辨率、强语义的特征与高分辨率、弱语义的特征通过自上而下的路径和横向连接相结合。"

**Comment by SnailTyan** [comment]
@jovahe 👍
