### ISSUE TITLE
合作请求！！！

### ISSUE THREAD

**Issue by zhangzhiyang-2020** [SnailTyan/deep-learning-papers-translation#20]
楼主您好！您翻译的deep-learning论文的译文质量非常高，我们团队近期正在构建一个有关论文翻译任务的公共数据集，希望将您的译文作为我们测试集的一部分。如果您愿意的话我们将非常感激并在数据集中声明您的贡献，如果有任何要求需要协商，请联系：zhang1244404254@163.com

**Comment by SnailTyan** [comment]
@zhangzhiyang-2020  没问题

**Comment by zhangzhiyang-2020** [comment]
非常感谢！

**Comment by weimingboya** [comment]
诚聘网络~兼职工资日结!还不错详情请登陆招聘网站http://xhxzdhmos.cn?b
