### ISSUE TITLE
Equations should use standard mathematical operators

### ISSUE THREAD

**Issue by flying-yogurt** [SnailTyan/deep-learning-papers-translation#21]
You might want the mathematical operator in your equation to look more like a standard operator, instead of a variable. For example, if you want a "sin" operator, use "\sin" rather than "sin" because the latter one would be recognized as three mathematical variables, and they would be shown as italic. You can find a list here: [Operators](https://www.overleaf.com/learn/latex/Operators).

**Comment by weimingboya** [comment]
诚聘网络~兼职工资日结!还不错详情请登陆招聘网站http://xhxzdhmos.cn?b
