### ISSUE TITLE
中文的链接都打不开

### ISSUE THREAD

**Issue by yhl41001** [SnailTyan/deep-learning-papers-translation#4]
中文的链接都打不开

**Comment by byte3125** [comment]
我看了一下faster rcnn的那篇，基本全是机翻。。。就这骗了六百多个star也是服了。。。

**Comment by SnailTyan** [comment]
@byte3125 你咋不翻译呢？论文我自己读的，翻译是谷歌翻译+人工翻译。觉得不好你可以提供更好的，自己不干挑毛病的不欢迎。

**Comment by SnailTyan** [comment]
@yhl41001 我这边都能打开，博客在github上，你打不开想想办法吧，可以翻墙。实在不行只能看[https://www.jianshu.com/c/2beb43385526](https://www.jianshu.com/c/2beb43385526)
